// GENERATED by scripts/build-sender-assets.py from dealer_data.json. Do not edit.
// One entry per unique primary email address.
const RECIPIENTS = [
 {
  "email": "info@autocentrumszabo.hu",
  "dealers": [
   {
    "code": "HUA2451",
    "name": "Autócentrum Szabó Csoport - Érd"
   }
  ]
 },
 {
  "email": "ertekesites@suzukifehervar.hu",
  "dealers": [
   {
    "code": "HUA8001",
    "name": "Autócentrum Szabó Csoport - Székesfehérvár"
   }
  ]
 },
 {
  "email": "suzuki@autohaz-barta.hu",
  "dealers": [
   {
    "code": "HUA9203",
    "name": "Autóház-Barta"
   }
  ]
 },
 {
  "email": "suzuki@dunaauto.hu",
  "dealers": [
   {
    "code": "HUA1034",
    "name": "Duna Autó Zrt."
   }
  ]
 },
 {
  "email": "benjamin.kovacs@inicial.hu",
  "dealers": [
   {
    "code": "HUA9407",
    "name": "ICL Autó Kft. - Sopron"
   }
  ]
 },
 {
  "email": "cegled@jansik.hu",
  "dealers": [
   {
    "code": "HUA2701",
    "name": "Jansik Autóház"
   }
  ]
 },
 {
  "email": "suzuki@jpauto.hu",
  "dealers": [
   {
    "code": "HUA3308",
    "name": "Jász-Plasztik Autócentrum - Eger"
   },
   {
    "code": "HUA5103",
    "name": "Jász-Plasztik Autócentrum - Jászberény"
   }
  ]
 },
 {
  "email": "suzuki@kevesauto.hu",
  "dealers": [
   {
    "code": "HUA6230",
    "name": "Kévés Autó Suzuki Soltvadkert"
   }
  ]
 },
 {
  "email": "suzukiszentes@gmail.com",
  "dealers": [
   {
    "code": "HUA6606",
    "name": "Kévés Autó Suzuki Szentes"
   }
  ]
 },
 {
  "email": "info@suzukikeszthely.hu",
  "dealers": [
   {
    "code": "HUA8303",
    "name": "Kor-Autó"
   }
  ]
 },
 {
  "email": "limuzin@limuzinautohaz.hu",
  "dealers": [
   {
    "code": "HUA4006",
    "name": "Limuzin Autóház"
   }
  ]
 },
 {
  "email": "suzuki@ringautohaz.hu",
  "dealers": [
   {
    "code": "HUA5006",
    "name": "Ring Autóház"
   }
  ]
 },
 {
  "email": "info@ringautokft.hu",
  "dealers": [
   {
    "code": "HUA8207",
    "name": "Ring-Autó Kft."
   }
  ]
 },
 {
  "email": "suzuki@siposauto.hu",
  "dealers": [
   {
    "code": "HUA9701",
    "name": "Sipos Autóház"
   }
  ]
 },
 {
  "email": "kisvardasuzuki@gmail.com",
  "dealers": [
   {
    "code": "HUA4603",
    "name": "Speciál Suzuki - Kisvárda"
   }
  ]
 },
 {
  "email": "specialmobil@gmail.com",
  "dealers": [
   {
    "code": "HUA4406",
    "name": "Speciál Suzuki - Nyíregyháza"
   }
  ]
 },
 {
  "email": "sarospatakisuzuki@gmail.com",
  "dealers": [
   {
    "code": "HUA3952",
    "name": "Speciál Suzuki Sárospatak"
   }
  ]
 },
 {
  "email": "bekescsaba@ankers.hu",
  "dealers": [
   {
    "code": "HUA5601",
    "name": "Suzuki Ankers - Békéscsaba"
   }
  ]
 },
 {
  "email": "oroshaza@ankers.hu",
  "dealers": [
   {
    "code": "HUA5901",
    "name": "Suzuki Ankers - Orosháza"
   }
  ]
 },
 {
  "email": "szeged@ankers.hu",
  "dealers": [
   {
    "code": "HUA6707",
    "name": "Suzuki Ankers - Szeged"
   }
  ]
 },
 {
  "email": "recepcio@autokoz.hu",
  "dealers": [
   {
    "code": "HUA9002",
    "name": "Suzuki Autóközpont"
   }
  ]
 },
 {
  "email": "info@suzukibarna.hu",
  "dealers": [
   {
    "code": "HUA6092",
    "name": "Suzuki Barna"
   }
  ]
 },
 {
  "email": "babik.robert@suzukibarta.hu",
  "dealers": [
   {
    "code": "HUA7031",
    "name": "Suzuki Barta - Paks"
   }
  ]
 },
 {
  "email": "suzukibarta@barta.hu",
  "dealers": [
   {
    "code": "HUA7007",
    "name": "Suzuki Barta - Sárbogárd"
   }
  ]
 },
 {
  "email": "szekesfehervar@barta.hu",
  "dealers": [
   {
    "code": "HUA8008",
    "name": "Suzuki Barta Székesfehérvár"
   }
  ]
 },
 {
  "email": "havasi.janos@suzukibarta.hu",
  "dealers": [
   {
    "code": "HUA7104",
    "name": "Suzuki Barta - Szekszárd"
   }
  ]
 },
 {
  "email": "info@suzukiborongics.hu",
  "dealers": [
   {
    "code": "HUA8602",
    "name": "Suzuki Borongics"
   }
  ]
 },
 {
  "email": "ertekesites.suzuki@autofort.hu",
  "dealers": [
   {
    "code": "HUA1046",
    "name": "Suzuki Carnet Auto-Fort"
   }
  ]
 },
 {
  "email": "bene.balazs@castrum-ferreum.hu",
  "dealers": [
   {
    "code": "HUA9704",
    "name": "Suzuki Castrum"
   }
  ]
 },
 {
  "email": "szerviz@diferujvaros.hu",
  "dealers": [
   {
    "code": "HUA2401",
    "name": "Suzuki Di-fer Márkakereskedés és Szerviz - Dunaújváros"
   }
  ]
 },
 {
  "email": "callcenter@di-fer.hu",
  "dealers": [
   {
    "code": "HUA2031",
    "name": "Suzuki Di-fer Márkakereskedés és Szerviz - Érd"
   }
  ]
 },
 {
  "email": "autoduna@autoduna.hu",
  "dealers": [
   {
    "code": "HUA1099",
    "name": "Suzuki Duna"
   }
  ]
 },
 {
  "email": "eszakker@eszakker.hu",
  "dealers": [
   {
    "code": "HUA3105",
    "name": "Suzuki Északker"
   }
  ]
 },
 {
  "email": "suzukinagykanizsa@fxautohaz.hu",
  "dealers": [
   {
    "code": "HUA7612",
    "name": "Suzuki FX Autóház - Nagykanizsa"
   }
  ]
 },
 {
  "email": "viktor.kolgyesi@fxautohaz.hu",
  "dealers": [
   {
    "code": "HUA7615",
    "name": "Suzuki FX Autóház - Pécs (Schroll J. út)"
   }
  ]
 },
 {
  "email": "suzukikomarom@geringer.hu",
  "dealers": [
   {
    "code": "HUA2902",
    "name": "Suzuki Géringer"
   }
  ]
 },
 {
  "email": "info@suzukigero.hu",
  "dealers": [
   {
    "code": "HUA1171",
    "name": "Suzuki Géro"
   }
  ]
 },
 {
  "email": "auto@suzukigusztav.hu",
  "dealers": [
   {
    "code": "HUA1162",
    "name": "Suzuki Gusztáv"
   }
  ]
 },
 {
  "email": "info@gyulaautohaz.hu",
  "dealers": [
   {
    "code": "HUA5701",
    "name": "Suzuki Gyula Autóház"
   }
  ]
 },
 {
  "email": "suzukihaz2000@gmail.com",
  "dealers": [
   {
    "code": "HUA1142",
    "name": "Suzuki Ház"
   }
  ]
 },
 {
  "email": "mail@suzukihirt.hu",
  "dealers": [
   {
    "code": "HUA7002",
    "name": "Suzuki Hirt"
   }
  ]
 },
 {
  "email": "info@suzuki-interat.hu",
  "dealers": [
   {
    "code": "HUA2062",
    "name": "Suzuki Interat - Márkakereskedés és Szerviz"
   }
  ]
 },
 {
  "email": "kaposauto@kapos-auto.hu",
  "dealers": [
   {
    "code": "HUA7401",
    "name": "Suzuki Kapos Autó"
   }
  ]
 },
 {
  "email": "karvalics@t-online.hu",
  "dealers": [
   {
    "code": "HUA7501",
    "name": "Suzuki Karvalics"
   }
  ]
 },
 {
  "email": "suzuki-konig@datatrans.hu",
  "dealers": [
   {
    "code": "HUA8003",
    "name": "Suzuki Kőnig"
   }
  ]
 },
 {
  "email": "info@kovesdan.hu",
  "dealers": [
   {
    "code": "HUA1224",
    "name": "Suzuki Kövesdán"
   }
  ]
 },
 {
  "email": "suzuki@licskaiautohaz.hu",
  "dealers": [
   {
    "code": "HUA9332",
    "name": "Suzuki Licskai Autóház"
   }
  ]
 },
 {
  "email": "ajka@marsal.hu",
  "dealers": [
   {
    "code": "HUA8403",
    "name": "Suzuki Marsal - Ajka-Bakonygyepes"
   }
  ]
 },
 {
  "email": "papa@marsal.hu",
  "dealers": [
   {
    "code": "HUA8502",
    "name": "Suzuki Marsal - Pápa"
   }
  ]
 },
 {
  "email": "meszarosautokft@gmail.com",
  "dealers": [
   {
    "code": "HUA8102",
    "name": "Suzuki Mészáros"
   }
  ]
 },
 {
  "email": "suzuki.molnar@t-online.hu",
  "dealers": [
   {
    "code": "HUA9301",
    "name": "Suzuki Molnár Autóház - Csorna"
   }
  ]
 },
 {
  "email": "suzuki.molnargyor@suzukimolnar.hu",
  "dealers": [
   {
    "code": "HUA9005",
    "name": "Suzuki Molnár Autóház - Győr"
   }
  ]
 },
 {
  "email": "suzukiperger@gmail.com",
  "dealers": [
   {
    "code": "HUA8203",
    "name": "Suzuki Perger"
   }
  ]
 },
 {
  "email": "suzukiertekesites@sandorservice.hu",
  "dealers": [
   {
    "code": "HUA5309",
    "name": "Suzuki Sándor"
   }
  ]
 },
 {
  "email": "suzukistabil111@gmail.com",
  "dealers": [
   {
    "code": "HUA9006",
    "name": "Suzuki Stabil"
   }
  ]
 },
 {
  "email": "auto@suzukistop.hu",
  "dealers": [
   {
    "code": "HUA4004",
    "name": "Suzuki Stop Autóház"
   }
  ]
 },
 {
  "email": "syscarmuszak@gmail.com",
  "dealers": [
   {
    "code": "HUA6501",
    "name": "Suzuki Syscar"
   }
  ]
 },
 {
  "email": "ertekesites@suzukicsepel.hu",
  "dealers": [
   {
    "code": "HUA1213",
    "name": "Suzuki Szabó Csepel"
   }
  ]
 },
 {
  "email": "suzukiszanto@suzukiszanto.hu",
  "dealers": [
   {
    "code": "HUA8902",
    "name": "Suzuki Szántó"
   }
  ]
 },
 {
  "email": "drycar2800@gmail.com",
  "dealers": [
   {
    "code": "HUA2854",
    "name": "Suzuki Száraz"
   }
  ]
 },
 {
  "email": "auto@szeleczky.hu",
  "dealers": [
   {
    "code": "HUA2151",
    "name": "Suzuki Szeleczky"
   }
  ]
 },
 {
  "email": "ertekesites@suzukiszigetvar.hu",
  "dealers": [
   {
    "code": "HUA7902",
    "name": "Suzuki Szigetvár"
   }
  ]
 },
 {
  "email": "ertekesites@suzukitafak.hu",
  "dealers": [
   {
    "code": "HUA1101",
    "name": "Suzuki Tafák"
   }
  ]
 },
 {
  "email": "lead@tormasi.hu",
  "dealers": [
   {
    "code": "HUA6005",
    "name": "Suzuki Tormási"
   }
  ]
 },
 {
  "email": "info@suzukivac.hu",
  "dealers": [
   {
    "code": "HUA2604",
    "name": "Suzuki Vác"
   }
  ]
 },
 {
  "email": "dealer@vagep.hu",
  "dealers": [
   {
    "code": "HUA4404",
    "name": "Suzuki Vagép"
   }
  ]
 },
 {
  "email": "suzukilanycsok@gmail.com",
  "dealers": [
   {
    "code": "HUA7606",
    "name": "Suzuki Varga - Kozármisleny"
   }
  ]
 },
 {
  "email": "suzukilany@gmail.com",
  "dealers": [
   {
    "code": "HUA7701",
    "name": "Suzuki Varga - Lánycsók"
   }
  ]
 },
 {
  "email": "info@suzuki-varro.hu",
  "dealers": [
   {
    "code": "HUA1185",
    "name": "Suzuki Varró - Nagykőrösi út 152."
   },
   {
    "code": "HUA1182",
    "name": "Suzuki Varró - Üllői út - 18. kerület"
   }
  ]
 },
 {
  "email": "veszpremi@suzuki-szeged.hu",
  "dealers": [
   {
    "code": "HUA6703",
    "name": "Suzuki Veszprémi Szeged"
   }
  ]
 },
 {
  "email": "info@suzukivilag.hu",
  "dealers": [
   {
    "code": "HUA2042",
    "name": "Suzuki Világ - Budaörs"
   }
  ]
 },
 {
  "email": "hajos.gellert@suzukivilag.hu",
  "dealers": [
   {
    "code": "HUA2509",
    "name": "Suzuki Világ - Esztergom"
   }
  ]
 },
 {
  "email": "info@szabosuzuki.hu",
  "dealers": [
   {
    "code": "HUA3701",
    "name": "Szabó Suzuki Kazincbarcika"
   },
   {
    "code": "HUA3505",
    "name": "Szabó Suzuki Miskolc"
   }
  ]
 }
];
