#!/usr/bin/env python3
"""Generate tracker/src/Dealers.js from data/dealer_data.json. Run: python3 scripts/build-dealers.py"""
import json
import pathlib
from urllib.parse import urlparse

ROOT = pathlib.Path(__file__).resolve().parent.parent


def city_of(d):
    lvl2 = d.get("addressLevel2") or {}
    name = (lvl2.get("name") or "").strip()
    if name:
        return name.title()
    return (d.get("addressLine1") or "").split(",")[0].strip()


def host_of(url):
    if not url:
        return ""
    host = urlparse(url if "://" in url else "https://" + url).hostname or ""
    return host.lower().removeprefix("www.")


dealers = []
for d in json.loads((ROOT / "data" / "dealer_data.json").read_text(encoding="utf-8")):
    if d.get("isArchived") or d.get("isTestDealer"):
        continue
    phone = d.get("primaryPhoneNumber") or ""
    dealers.append({
        "code": d["code"],
        "name": d["name"].strip(),
        "city": city_of(d),
        "address": (d.get("addressLine1") or "").strip(),
        "email": (d.get("primaryEmail") or "").strip().lower(),
        "serviceEmail": (d.get("servicePrimaryEmail") or "").strip().lower(),
        "phone": f"{d.get('countryCallingCodePrimary', '+36')} {phone}".strip() if phone else "",
        "website": d.get("websiteUrl") or "",
        "websiteDomain": host_of(d.get("websiteUrl")),
        "lat": d.get("latitude"),
        "lng": d.get("longitude"),
    })

out = ROOT / "tracker" / "src" / "Dealers.js"
out.write_text(
    "// GENERATED by scripts/build-dealers.py from dealer_data.json. Do not edit by hand.\n"
    f"const DEALERS = {json.dumps(dealers, ensure_ascii=False, indent=1)};\n",
    encoding="utf-8",
)
print(f"Wrote {len(dealers)} dealers to {out.relative_to(ROOT)}")
