#!/usr/bin/env python3
"""Generates sender/src/Recipients.js (unique dealer emails) and sender/src/Attachment.js (embedded PDF).

Usage: python3 scripts/build-sender-assets.py [path/to/config.pdf]
"""
import base64
import glob
import hashlib
import json
import os
import re
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "sender", "src")
EMAIL_RE = re.compile(r"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$")


def build_recipients():
    with open(os.path.join(ROOT, "dealer_data.json"), encoding="utf-8") as f:
        dealers = json.load(f)
    by_email = {}
    for d in dealers:
        email = (d.get("primaryEmail") or "").strip().lower()
        if not EMAIL_RE.match(email):
            sys.exit(f"Invalid or missing email for {d.get('code')}: {email!r}")
        by_email.setdefault(email, []).append({"code": d["code"], "name": d["name"].strip()})
    recipients = [{"email": e, "dealers": ds} for e, ds in by_email.items()]
    with open(os.path.join(OUT, "Recipients.js"), "w", encoding="utf-8") as f:
        f.write("// GENERATED by scripts/build-sender-assets.py from dealer_data.json. Do not edit.\n")
        f.write("// One entry per unique primary email address.\n")
        f.write("const RECIPIENTS = " + json.dumps(recipients, ensure_ascii=False, indent=1) + ";\n")
    print(f"Recipients.js: {len(recipients)} unique addresses ({len(dealers)} dealers)")


def build_attachment(pdf_path):
    with open(pdf_path, "rb") as f:
        data = f.read()
    if not data.startswith(b"%PDF"):
        sys.exit(f"Not a PDF: {pdf_path}")
    sha = hashlib.sha256(data).hexdigest()
    b64 = base64.b64encode(data).decode("ascii")
    with open(os.path.join(OUT, "Attachment.js"), "w", encoding="ascii") as f:
        f.write("// GENERATED by scripts/build-sender-assets.py. Do not edit.\n")
        f.write("// Source: " + unicodedata.normalize("NFC", os.path.basename(pdf_path)).encode("ascii", "replace").decode() + "\n")
        f.write(f"const ATTACHMENT_SHA256 = '{sha}';\n")
        f.write(f"const ATTACHMENT_BYTES = {len(data)};\n")
        f.write(f"const ATTACHMENT_BASE64 = '{b64}';\n")
    print(f"Attachment.js: {len(data)} bytes, sha256 {sha}")


if __name__ == "__main__":
    pdf = sys.argv[1] if len(sys.argv) > 1 else None
    if not pdf:
        found = [p for p in glob.glob(os.path.join(ROOT, "*.pdf")) if "Konfigur" in unicodedata.normalize("NFC", p)]
        if len(found) != 1:
            sys.exit("Pass the configuration PDF path explicitly.")
        pdf = found[0]
    os.makedirs(OUT, exist_ok=True)
    build_recipients()
    build_attachment(pdf)
